"""Supply chain: lockfile, SBOM and licence gate (audit #103, #107, #108). Run from repo root:

    python backend/scripts/supply_chain.py lock      # requirements.lock = full transitive closure, exact versions
    python backend/scripts/supply_chain.py sbom      # sbom.cdx.json  (CycloneDX 1.5, incl. vendored JS)
    python backend/scripts/supply_chain.py licenses  # fails if any dependency has a copyleft / unknown licence

Uses only the standard library (importlib.metadata) so it runs on an air-gapped build host.
"""
from __future__ import annotations

import datetime
import importlib.metadata as md
import json
import re
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ALLOWED = ("MIT", "BSD", "Apache", "PSF", "Python Software Foundation", "ISC", "MPL-2.0", "Unlicense", "HPND")
DENIED = ("GPL", "AGPL", "LGPL", "SSPL", "Commons Clause", "BUSL")
# licences that packages ship as a text blob instead of an SPDX id (verified by hand)
KNOWN = {"numpy": "BSD-3-Clause", "scipy": "BSD-3-Clause", "idna": "BSD-3-Clause", "annotated-types": "MIT",
         "sniffio": "MIT OR Apache-2.0", "certifi": "MPL-2.0", "packaging": "Apache-2.0 OR BSD-2-Clause"}
VENDORED = [  # frontend/vendor - shipped inside the product, no CDN
    {"name": "react", "version": "18.3.1", "license": "MIT", "file": "frontend/vendor/react.js"},
    {"name": "react-dom", "version": "18.3.1", "license": "MIT", "file": "frontend/vendor/rdom.js"},
    {"name": "htm", "version": "3.1.1", "license": "Apache-2.0", "file": "frontend/vendor/htm.js"},
    {"name": "three", "version": "0.128.0", "license": "MIT", "file": "frontend/vendor/three.js"},
    {"name": "three-orbitcontrols (examples/js, r128)", "version": "0.128.0", "license": "MIT", "file": "frontend/vendor/orbit.js"},
]


def _top_level(path: Path) -> list[str]:
    out = []
    for line in path.read_text().splitlines():
        line = line.split("#")[0].strip()
        if line and not line.startswith("-"):
            out.append(re.split(r"[=<>\[; ]", line)[0])
    return out


def _norm(n: str) -> str:
    return re.sub(r"[-_.]+", "-", n).lower()


def closure(roots: list[str]) -> dict[str, str]:
    seen: dict[str, str] = {}
    stack = list(roots)
    while stack:
        name = _norm(stack.pop())
        if name in seen:
            continue
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            continue
        seen[name] = dist.version
        for req in dist.requires or []:
            if "extra ==" in req:
                continue
            if ";" in req and ("sys_platform" in req or "python_version" in req or "platform" in req):
                cond = req.split(";", 1)[1]
                try:
                    if not eval(cond.replace("sys_platform", repr(sys.platform))
                                .replace("platform_system", repr(__import__("platform").system()))
                                .replace("python_version", repr(".".join(map(str, sys.version_info[:2]))))):
                        continue
                except Exception:
                    pass
            stack.append(re.split(r"[=<>!~\[; (]", req.strip())[0])
    return dict(sorted(seen.items()))


def licence(name: str) -> str:
    if name in KNOWN:
        return KNOWN[name]
    meta = md.metadata(name)
    lic = meta.get("License-Expression") or ""
    if not lic:
        cls = [c.split("::")[-1].strip() for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
        lic = " / ".join(cls) or (meta.get("License") or "").splitlines()[0][:60] if (meta.get("License") or cls) else ""
    return lic or "UNKNOWN"


def main(cmd: str) -> int:
    pkgs = closure(_top_level(ROOT / "requirements.txt"))
    if cmd == "lock":
        (ROOT / "requirements.lock").write_text(
            "# generated by backend/scripts/supply_chain.py lock - install with: pip install --no-deps -r requirements.lock\n"
            + "".join(f"{n}=={v}\n" for n, v in pkgs.items()))
        print(f"requirements.lock: {len(pkgs)} packages")
    elif cmd == "sbom":
        comps = [{"type": "library", "name": n, "version": v, "purl": f"pkg:pypi/{n}@{v}",
                  "licenses": [{"expression": licence(n)}]} for n, v in pkgs.items()]
        comps += [{"type": "library", "name": x["name"], "version": x["version"], "purl": f"pkg:npm/{x['name']}@{x['version']}",
                   "licenses": [{"expression": x["license"]}], "properties": [{"name": "vendored", "value": x["file"]}]}
                  for x in VENDORED]
        bom = {"bomFormat": "CycloneDX", "specVersion": "1.5", "serialNumber": f"urn:uuid:{uuid.uuid4()}", "version": 1,
               "metadata": {"timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                            "component": {"type": "application", "name": "sovereign-optimizer", "version": "0.3.0"}},
               "components": comps}
        (ROOT / "sbom.cdx.json").write_text(json.dumps(bom, indent=1))
        print(f"sbom.cdx.json: {len(comps)} components")
    elif cmd == "licenses":
        bad = []
        for n in pkgs:
            lic = licence(n)
            ok = any(a.lower() in lic.lower() for a in ALLOWED) and not any(d in lic for d in DENIED)
            print(f"{'ok ' if ok else 'BAD'} {n:24s} {pkgs[n]:10s} {lic}")
            if not ok:
                bad.append(n)
        for x in VENDORED:
            print(f"ok  {x['name']:24s} {x['version']:10s} {x['license']}  (vendored)")
        if bad:
            print(f"\nlicence gate FAILED for: {', '.join(bad)} - review, then allow-list in KNOWN if acceptable")
            return 1
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else ""))
